### ISSUE TITLE
deletecommand does not find the stored file

### ISSUE THREAD

**Issue by BNNorman** [connected-little-boxes/box-code#5]
```
stores
Processing: stores

 Store:/start
   Command:/start/liftoff
      {"process":"servo","command":"setservopos","value":0}
deletecommand liftoff
Processing: deletecommand liftoff

File:liftoff not found
```

doesn't work with start/liftoff either

**Comment by CrazyRobMiles** [comment]
There's an issue with LittleFS. The filename reported on a directory entry is different across ESP8266 and ESP32 devices. This caused the delete command to fail to find the file for deletion. 
Fixed.

**Comment by BNNorman** [comment]
What is the difference?

**Comment by CrazyRobMiles** [comment]
The ESP32 version gives the full path to the file when you ask for its name from the directory entry. The ESP8266 just gives the filename itself.

**Comment by BNNorman** [comment]
Ah, so your code would add the top level folder so you get start/start/file?

Can you add a conditional compilation thing so that when compiling for ESP32 it doesn't do that?

**Comment by CrazyRobMiles** [comment]
Not sure. But I've fixed it anyway.
