### ISSUE TITLE
ezTime library not installing

### ISSUE THREAD

**Issue by BNNorman** [connected-little-boxes/box-code#9]
I know I mentioned capitalisation of m5ez/ezTime in platform.ini before but it still doesn't work for me.

However, ropg/ezTime does install.

**Comment by CrazyRobMiles** [comment]
Just discovered this myself when I installed a new version in an empty folder. It should be ropg. I'll rename it.

**Comment by BNNorman** [comment]
Ha ha - always good to do a checkpoint.
